apiVersion: v1
kind: Service
metadata:
  name: grafana-loadbalancer
  namespace: default
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
